### ISSUE TITLE
Create test for find_links function

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/explorer#7]
Create script `test.py` which will test function find_links when run as:

```sh
python script/test.py
```

It should print
```sh
All tests done.
```
If tests passes old
```sh
Error in find_links
```
If the links found page are not the links which are expected.

**Comment by AnnaLangner** [comment]
I added a counter to see how many links there are on the page. A similar number came out as I counted manually

**Comment by AnnaLangner** [comment]
When I import a function from main.py, it imports the entire file instead of one function and I get a required driver and url error in the console. If I enter these two arguments, the entire main.py file runs first, then test_count_links :( what am I doing wrong?

When I changed test_find_links to get a function from import, the counter doesn't get the value from the function :(

**Comment by klangner** [comment]
Yes, because main is executed when the file is imported.
The solution to this is to execute main only when it is run as main file.
You can do this with the following code:
```python
if __name__== "__main__":
  main()
```
More information:
https://www.guru99.com/learn-python-main-function-with-examples-understand-main.html
